### ISSUE TITLE
[Add] Add an option to add a background color not affected by transition 

### ISSUE THREAD

**Issue by Iam-Muslim** [rebinf/QuranVideoMaker#13]
Aslam alaikom my brother , 

- <del>make the transition optionally before adding ayas (</del>

- If i add a background color , it will be affected with transition , you can add an option for this to enabe it or disable it ( make the color static )

**Comment by rebinf** [comment]
I've split this into two as they are separate issues.
See #18

**Comment by rebinf** [comment]
Completed in [#412e93397399de9aa26511714e926afe90a3edf2](https://github.com/rebinf/QuranVideoMaker/commit/412e93397399de9aa26511714e926afe90a3edf2)
