### ISSUE TITLE
Color changing not saved

### ISSUE THREAD

**Issue by rebinf** [rebinf/QuranVideoMaker#17]
See #12

**Comment by Iam-Muslim** [comment]
Jazaak Allah Khairn for fast responding . 
I didn't split to not make alot of issues there :D
but i didn't mean the color changing i meant defining a new color
This when i define 

![image](https://github.com/rebinf/QuranVideoMaker/assets/98652126/8b16865f-7d1e-4bb5-918d-4f93d9eb0745)

and after pressing ok and going to colors again , it is not saved in custom colors

![image](https://github.com/rebinf/QuranVideoMaker/assets/98652126/b9e7b897-8283-4dec-88d8-3c7682d96d9b)

**Comment by rebinf** [comment]
Wa iiyakum,

Defined colors are now saved as part of the project #21.

Many issues is fine, that way we can track each issue separately.
