### ISSUE TITLE
Making/Installing [Ubuntu}

### ISSUE THREAD

**Issue by r4n078dom** [rebinf/QuranVideoMaker#2]
Hi I have tried making/installing this but I cannot seem to do it. Please could anyone help?

**Comment by rebinf** [comment]
This only works on windows.

**Comment by r4n078dom** [comment]
What are the steps on windows?

**Comment by r4n078dom** [comment]
I cannot find the .exe file, I am a bit new to this so your help would be much appreciated

**Comment by rebinf** [comment]
I've released a [self contained version](https://github.com/rebinf/QuranVideoMaker/releases/tag/v0.0.3).
Also added the [installation instructions](https://github.com/rebinf/QuranVideoMaker#installation).
It's simple, download and extract the zip file and run `QuranVideoMaker.exe`.

**Comment by r4n078dom** [comment]
Thank you so much
I have managed to get it working
May Allah reward you!

**Comment by rebinf** [comment]
Happy to hear you got it working.
Thank you, you too.

**Comment by GuerfiHamza** [comment]
Hello i cannot find the QuranVideoMaker.exe
