### ISSUE TITLE
Switch to ubuntu runner

### ISSUE THREAD

**Issue by rebinf** [rebinf/QuranVideoMaker#20]
Waiting on https://github.com/dotnet/runtime/pull/89303

**Comment by Iam-Muslim** [comment]
Alslamo alaikom ,
i have an Windows/Linux RDP(VPS) for one month ...
if you need it i can send you the ip , user and password

**Comment by rebinf** [comment]
Wa alaykum salam,

Once net 8.0 goes GA, QVM should be able to be built on github actions using ubuntu.

Thank you for your kindness.
JazakAllahu khayran
