### ISSUE TITLE
a c# project using ffmpeg

### ISSUE THREAD

**Issue by Iam-Muslim** [rebinf/QuranVideoMaker#25]
Alslam alaikom , 

This project uses many of ffmpeg functions in c#

you can search for hardware acceleration and nvenc for using their classes for improving exporting using the gpu accelration insha' Allah

[https://github.com/MattMcManis/Axiom](url)

**Comment by rebinf** [comment]
Turns out, I was putting the hardware acceleration option in the wrong place.

JazakAllahu Khayran

**Comment by Iam-Muslim** [comment]
Alslamo alaikom my brother <3 , 
May Allah (subhanuh ) bless you .
Also you can get from this repo some other functions for handling good export speeds , handling exceptions , some quality changes and ......

**Comment by rebinf** [comment]
Wa alaykum salam,
same to you.

I'll keep that tool in mind for future references, i.e when adding more export options.
