### ISSUE TITLE
Export stuck

### ISSUE THREAD

**Issue by Iam-Muslim** [rebinf/QuranVideoMaker#31]
Exporting stucks when exporting a long surah in a high resolution 
you can try maybe 4k and more than 1 hour surah to test this

**Comment by rebinf** [comment]
As mentioned before, higher quality and longer length videos require a lot of RAM, you've very likely ran out of RAM while exporting.

**Comment by Iam-Muslim** [comment]
yea i know the problem but we need to finnd a fix for that  😂 ❤️

**Comment by Dgriffin88** [comment]
How do I find it

**Comment by rebinf** [comment]
may be duplicate of #39 please try the latest update, if any problems, create another issue.
