### ISSUE TITLE
QuranVideoMaker.exe missing ?

### ISSUE THREAD

**Issue by ibroche** [rebinf/QuranVideoMaker#32]
Hi, I cant find the exe file in the zip file. Is it normal ? thx

**Comment by rebinf** [comment]
Hi, the file `.exe` extension may only show if you have enabled `File name extensions` option in windows.
Anyway, it either appears as `QuranVideoMaker.exe` or `QuranVideoMaker`
Hope this helps.

![image](https://github.com/rebinf/QuranVideoMaker/assets/16520022/f818a38f-8832-4c39-a86b-9a1457de095d)
