### ISSUE TITLE
I cannot find EXE File

### ISSUE THREAD

**Issue by shahsaudzaman** [rebinf/QuranVideoMaker#37]
Hey brother, please help me here may Allah bless u. I cannot find the exe file, nor the icon. How do I open the editor?

**Comment by rebinf** [comment]
Go to releases page and download the latest version, make sure to download the zip file under Assets section, unzip the file into a directory in that directory the exe file has a green icon like what you see in the README file in this repo.
You may not see the `.exe` at the end of the file name if your OS is hiding known file extensions.
