### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by mabdu26** [rebinf/QuranVideoMaker#39]
I'm trying to export my quran recitation and it loads until the green bar is full, and then I find no file in the file location. Tried multiple times with different file locations and resolutions.

**Comment by rebinf** [comment]
I think the progressbar fills up twice, at the end you should get a message saying it was successful.
Try that, otherwise let me know how long the video is and at what resolution.
Also how much RAM you have.

**Comment by mabdu26** [comment]
@rebinf I have 16gb ram and the video is 38 seconds long surah fatiha.  What happens is I get both the loading bars and then the second loading bar is stuck at full, I don't see the message saying its successful. Maybe is the number of threads- what do you recommend,  I put 4. Hardware acceleration at auto, encoding speed at medium.

**Comment by rebinf** [comment]
I just made a 42 second video in 4K, seems to be working as expected.
Try to put to set threads to -1 and see what happens.
Also, maybe give it a minute after the second progressbar finishes and see.

**Comment by myvideosgallery** [comment]
I’ve had the same issue with exporting the video on different computers. Even after the second progress bar fills up, no file is created. I’ve tried changing settings like the number of threads and hardware acceleration, but it’s still stuck. Please email me at myvideosgallery@gmail.com so we can try to figure this out together.![image](https://github.com/rebinf/QuranVideoMaker/assets/161176547/355aa3e2-e051-49f3-a991-2d99bfe0da88)

**Comment by rebinf** [comment]
I think this may because you have no audio file. So it seems to just fail silently and that's why it seems stuck.
I've just released an update, which will allow you export the video without an audio file, and it should it also let you know when it fails.

Download the new update and let me know.

Thanks for the screenshot, I think that helped to diagnose the issue.

**Comment by myvideosgallery** [comment]
It's functioning properly, appreciate it.

Could you also include the capability to choose aspect ratios such as 9:16 or portrait orientations for generating mobile videos? Is that achievable?
![image](https://github.com/rebinf/QuranVideoMaker/assets/161176547/0acd4ba8-38b0-48ed-9394-0953bdb14256)

**Comment by rebinf** [comment]
I've just released an update.
It allows you to define your own custom resolution.
It doesn't allow you to define your own custom aspect ratio at the moment, but it maintains aspect ratio of the videos/pictures you use.

**Comment by myvideosgallery** [comment]
I got exactly what I needed. Thank you so much—it's working perfectly now. Everything's taken care of. Thanks, buddy.

**Comment by rebinf** [comment]
No worries, glad to be of help.

**Comment by rebinf** [comment]
@mabdu26, you might want to try the latest update.
