### ISSUE TITLE
Trim Option not working

### ISSUE THREAD

**Issue by redaamrmahmoud** [rebinf/QuranVideoMaker#4]
Al slam alaikom my brother , 
May Allah Bless you for this work 

Trim Function for audio seems to work but when playing the audio it  continues playing the trimmed audio even it is trimmed/hidden .
Insha'a Allah i will contribute with you after my exams

**Comment by rebinf** [comment]
Wa alaykum salam.

Thank you for reporting this.

I've just released an update that should fix some of the audio track issues.

Please create an issue if you find anything else.

I think I might be rewriting some of the code as it has a lot of issues, if you're planning to contribute any code, you might want to create an issue to discuss it first.

Jazak Allahu khayran
