### ISSUE TITLE
Add black overlay to make text easier to see

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#40]
Assalamualaikum wbt brother, I have been using this for a while and I deeply respect you and pray that Allah blesses you for this! I have been having an issue that with a video with a slightly lighter/brighter background, nobody can read the text which is white. White is the best colour for the text, so I don't want to change it. Is it possible if you could add an option to have a black overlay over the video, but behind the text, then increase opacity so the video is darkened slightly but the text is much more visible then. This could be customised so that you can change the colour of overlay, or at least amount of opacity. At least a set opacity overlay that makes text easier to see would be very beneficial, like a tick box option for black overlay with set opacity or not. Also, another separate request is to have ayah numbers as well (again maybe a tick box option for it) included with the text, again I would greatly appreciate it. The first image is an example of when it is hard to read, and second image is an example of good example of even with white background, black overlay makes text easier to read, and also an example of ayah number with it. I know this is a lot, but these are the main things I think would hugely improve this software. Jazakhallah khair!
![hard to read text](https://github.com/user-attachments/assets/03671f8f-3edf-4696-b17f-86c7b8ade7de)
![image](https://github.com/user-attachments/assets/ff7cd543-764d-40e5-b89f-056ccd53b278)

**Comment by Farfighters** [comment]
![godd example](https://github.com/user-attachments/assets/93df9f75-a6e2-408a-b502-e515a9e06290)

**Comment by Farfighters** [comment]
There are other examples where the background is even whiter and it is extremely hard to read the text, this is just from my most recent video

**Comment by rebinf** [comment]
Wa alaykum salam,

To make text stand out a bit more you can change "Text Shadow Offset" property and you should get something similar to the below screenshot.
![Screenshot 2024-11-09 220122](https://github.com/user-attachments/assets/09a6d661-338d-464b-8df2-3db7fd2c3f91)

However, that can still be a bit difficult to see, so no you can set "Text Background" property to true and get something like:
![Screenshot 2024-11-09 235338](https://github.com/user-attachments/assets/85d97072-cb55-4550-83b8-52ee2c17130f)

And as you can already see, I've added the verse numbers option.

Thank you for your kind words.
Wa jazakAllah khayran

**Comment by Farfighters** [comment]
Assalamualaikum wbt brother. Subhanallah, you have made it next level, allahumabarik! Jazakhallah khair for doing it so quickly. 
I was testing out the new update and it is so much better now, but there were just a few issues with it that I just wanted to raise, I'm not sure whether you already know about them. Firstly, even when verse number is selected, only the first verse shows the verse number, the rest don't show it. Secondly, when verse transitions are on, the text background that makes text easier to read also fades out and back in. It makes watching it a bit distracting, maybe we could try and make another tick box for text background fading in or out as well. Because depending on how you use it, you may want it to fade out and in if it is only for text, but the way I have used it attached it doesn't look good, as the entire screen fades in and out. When verse transitions are off, then it is fine as there is no fading in and out of background. In some videos it might be ok, but some other videos it is very obvious, that's why I'm concerned. Please see what I mean (skip audhubillah and basmallah as there's no video there). Sorry for bad quality, I can only upload max 10MB:

https://github.com/user-attachments/assets/66201acf-53b0-4f81-bf2b-f1e3289908e1

https://github.com/user-attachments/assets/d27ed883-0e21-4b03-bfba-6a52f2923f2c

I have also added what it looks like without text background to show the massive improvement mashallah!

https://github.com/user-attachments/assets/d49ee507-6796-4c4b-9da5-57f5deb4341c

Jazakhallah khair for all your help brother!

**Comment by rebinf** [comment]
Wa alaykum salam,

Unfortunately I did not manage to replicate any of the issues you mentioned here.
Here is an example project:


Here is an example with text background, verse transition and verse numbers.
https://github.com/user-attachments/assets/b6bda393-a33a-4ef0-9145-315e9bdf09c9

Here is an example without text background, verse transition and verse numbers.
https://github.com/user-attachments/assets/0d676ff1-9e3e-45f9-b3ac-77d2e3568864

Here are the project files:
[TestProject1.zip](https://github.com/user-attachments/files/17692125/TestProject1.zip)

Please open a new issue for each proplem you are facing, and even better upload a test project demonstarting the issue. 
Again, thanks for your kind words, wa jazakAllah khayran.

**Comment by Farfighters** [comment]
Inshallah I will make new issue and post project there, but how do I upload the project? As the .qv file that it saves as?

**Comment by rebinf** [comment]
The qv and the project files (audio, video) if you can.
Just zip it up and upload it like I've done it in my previous comment.
