### ISSUE TITLE
Verse numbers not appearing

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#42]
I think you will have to create a folder in the Quran folder of your computer called TestProject100 to open the .qv, I had to do that for your one too. I have set text background padding to 1500 to fill the entire screen, and also ticked verse numbers:
[TestProject100.zip](https://github.com/user-attachments/files/17702967/TestProject100.zip)
I used auto verse to add verses, not sure whether that makes a difference or not.

**Comment by rebinf** [comment]
Yes, folder structure should match, as it needs to find the files in expected places, so that's why I thought `C:\Quran` would be an apporperiate place.
This was an issue with auto verse and it has been fixed.
Thank you for reporting it.
