### ISSUE TITLE
Add Ctrl+Z and reverse of that (maybe also Ctrl+C if possible)

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#44]
Assalamualaikum wbt brother. Could you add Ctrl+Z to undo previous actions, as if you accidentally delete something then you have to redo entire project. Also add reverse of that, redo. Some softwares use Ctrl+Shift+Z or Ctrl+Y for redo, so if you undid something but wanted to redo it, you can just Ctrl+Y. This is just a quality of life suggestion, I'm just thinking of different things that would make life a lot easier, but you already solved my main issues before, jazakhallah khair!

**Comment by rebinf** [comment]
Wa alaykum salam,
Thanks for the suggestion, I will look into it at some point insha'Allah.
Wa iiyakum

**Comment by Farfighters** [comment]
Jazakhallah khair

**Comment by Farfighters** [comment]
I was just checking the latest release for cut/copy/paste. Just wanted to report issue that whilst right clicking or using edit tool at top to do these actions are working fine alhamdulillah, the shortcuts are not working. If I do Ctrl+C or Ctrl+V it isn't working. Just wanted to let you know if you didn't know already, but you probably do!
