### ISSUE TITLE
Are we able to add multiple audio tracks in 1 project?

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#45]
I tried adding 2 but the second would start from the time wherever the last audio track finished. i.e. surah ikhlas finished at 30s, and when i put the start of surah falaq track to end of surah ikhlas track, the timing started from 30s and not frrom start.

**Comment by rebinf** [comment]
I'm aware of various audio issues, at the moment it only works if you just add an already edited and ready audio file.
I'll have a look and see if I can fix these issues at some point, insha'Allah

**Comment by Farfighters** [comment]
Jazakhallah khair
