### ISSUE TITLE
Transparent background colour

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#46]
Is it possible to add transparent background colour? Currently, if I want to use the quran verses without any background, I would either have to put a green screen behind for best results, or use plain black and in another software remove the green or black background so I can overlay the verses over something else which I can't do in QVM software. The problem with this is that the quality isn't as good, especially the verse transition, to the point where it isn't really usable. But if transparent background was added (similar to pictures which have transparent background), then you can overlay it straight away onto other videos and it would retain it's quality. Just another improvement I was thinking of. Again, jazakhallah khair for you time brother!

**Comment by rebinf** [comment]
I'm not quite sure if I quite understand the request here, are we talking about adding PNG images with transparency? Or are we talking about adding transparency/opacity to track items? Or are we talking about chroma keying (green screen)?

**Comment by Farfighters** [comment]
Sorry, I was saying a lot and made it quite confusing. I don't really understand most of what you said, I've just started video editing... But essentially I'm trying to overlay the verses on other videos without needing to do anything else to it, so it would already have transparent background when exported. I'm not sure that helps? Basically when the video is exported, it has the verses and audio track, but the background is transparent so it is ready to be an overlay in other softwares? Sorry if this doesn't help...

**Comment by rebinf** [comment]
No worries, I'm not an expert either :)
For what you're trying to achieve it's probably better to be able to export all the verses as PNGs with transparency, so you can import them into your video editor.
So I will look into adding this option soon insha'Allah.

**Comment by rebinf** [comment]
The PNGs are just images that can have transparency, you can import these into your video editor, add audio and edit it however you want.
Here is an example using kdenlive:

![image](https://github.com/user-attachments/assets/2d0268cc-8907-4925-9d89-3c30b7440db7)

Also, QVM source already includes batch verse generation already (I'll compile and include it very soon inshaAllah):

![image](https://github.com/user-attachments/assets/b300b837-7ea7-4ac2-9674-1933ea006359)

**Comment by Farfighters** [comment]
Ah I understand what you are talking about. That's what I want, but is there any way to have verse transition without having to manually fade in and out on the other video editor. Alhamdulillah the main reason I use QVM is because it is so easy to have verse transition compared to all these other softwares. But what you are showing is basically what I was thinking about!

**Comment by Farfighters** [comment]
I'm not sure whether it's possible, but is there a way when you export you keep that as a property of the chain of images? Maybe it already is in what you have shown, I just down know how to do that then

**Comment by rebinf** [comment]
> I'm not sure whether it's possible, but is there a way when you export you keep that as a property of the chain of images? Maybe it already is in what you have shown, I just down know how to do that then

Sorry, not really sure what you mean

**Comment by Farfighters** [comment]
Jazakhallah khair for you help again. I fully understand that this software is just to make it easier to make videos, and alhamdulillah it has accomplished that. Is it possible if instead of WEBM it exports as MOV or QuickTime which can still (but MOV would be better)? Some video editors don't support WEBM. Also, when playing the video in WEBM, verse instantly changes instead of fading like in video preview. The PNGs work perfectly, jazakhallah khair for that!

https://github.com/user-attachments/assets/69186822-348c-46e3-97d2-dc13710f23ba

It says it is MP4, but the video editor I'm using isn't uploading it, and I know it isn't compatible with WEBM. I'm using Davinci Resolve 19, it accepts MOV, I think that should be able to handle transparency? Because if this works, for extremely long and big videos which QVM can't handle well, in other video editors it would be a breeze to make Qur'an videos thanks to this. I hope this isn't too much to ask from you brother!

**Comment by Farfighters** [comment]
Playing this on the browser it is working, but on my laptop in media player it there is no verse transition. But using Clipchamp everything works fine, I converted to MOV then it worked, but verse transitions still not working? Maybe if it natively exports as MOV it should be ok?

**Comment by rebinf** [comment]
The file itself is fine, but it has the wrong extension, latest update should export with the correct extension.
I've added the option to select export formats (currently mp4, mov, webm).
Try the latest update and let me know.
Wa iiyakum

**Comment by Farfighters** [comment]
Jazakhallah khair, now it is working perfectly! Inshallah this will really speed up the editing process.

**Comment by rebinf** [comment]
wa iiyakum, happy it's working.
