### ISSUE TITLE
Better import options

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#48]
Currently it only accepts .mp3 and .mp4, could you allow it to also accept .wav and .mov? Some of the software and websites I use only give out .mov, .wav is fine if we don't get it, but I was just thinking if you would already be doing .mov you could add .wav? It also takes quite long to import anything, I tried seeing what makes it take longer, whether it is the resolution or length of video, but there are varying results. But if you could at least add .mov so we can import media files that would be perfect, jazakhallah khair!

**Comment by Farfighters** [comment]
Jazakhallah khair for this working perfectly! Alhamdulillah all your objectives with this have been met every single time mashallah!

**Comment by rebinf** [comment]
wa iiyakum

**Comment by Farfighters** [comment]
For some reason some videos I'm trying to import which are bigger than 250MB aren't importing correctly
![image](https://github.com/user-attachments/assets/71d28f0f-1893-48e7-a591-d3e15bf87bf1)
If you see in media pool there is a .mov that hasn't been exported properly and when I pull onto timeline it doesn't allow me to drop it in

**Comment by Farfighters** [comment]
Now saving works, but it keeps saying this now:
![image](https://github.com/user-attachments/assets/206a852e-630c-4fb1-99d1-7414f33a20df)
Not sure what that is to do with? I'm trying to export only ayahs with alpha channel and audio track

**Comment by Farfighters** [comment]
I'm not really sure why, but now all exporting is not working anymore, it keeps saying the same thing no matter which version I use

**Comment by Farfighters** [comment]
It is sometimes causing my laptop to crash now as well. I'm not sure what has happened, as everything else on my laptop is fine, looks like the software is causing some trouble.

**Comment by rebinf** [comment]
Could you please let us know how much RAM is available on the system?

**Comment by rebinf** [comment]
Yes 32GB should be enough, though somehow it's running out of memory.
![image](https://github.com/user-attachments/assets/a58e654a-db03-4668-b279-92b1f7331dcb)

it's ok, no need to send any videos, I'll try to find some big videos to test, thank you.

**Comment by Farfighters** [comment]
I did some tests as I had some time just now looking at task manager and I realised that what is happening is that normally (exporting mp4 and no alpha channel), it takes around 8-9 GB of RAM. Then when I export as mov (no alpha channel), it takes about 12-17GB  of RAM, and with both mov and alpha channel then it takes up around 24 or above GB of RAM. I also tried alpha channel and mp4 (though I know this doesn't actually work for transparency), it took around 20GB of RAM. So it looks like alpha channel is the main problem, it is using too much RAM for exporting, maybe unlimited as it just keeps increasing. On a side note, in all cases I was able to fully export, but I think it is because it was only for less than 30s as it was very short video, so maybe longer export takes, more RAM alpha channel takes up, same with mov but it starts of at around 15GB and slowly increases. Hopefully this helps inshallah!

**Comment by Farfighters** [comment]
It crashes after about 3 minutes of exporting at 26GB RAM!

**Comment by Farfighters** [comment]
If I limit amount of threads does that help or make it worse? I tried -1 and 10 but I saw no difference. I don't know how many my laptop has but I know it has 10, so I use that. Any other setting that can maybe reduce RAM? Maybe it could stop the software from crashing temporarily whilst you make a solution inshallah

**Comment by Farfighters** [comment]
If I somehow managed to limit RAM usage from outside, would that help it or make it crash quicker, maybe as it doesn't have enough RAM so it crashes instead of the laptop?

**Comment by rebinf** [comment]
limiting the memory is not going to work as the app is still going to crash as it runs out of memory.
Since this issue is somewhat unrelated and already closed, I've create #57 to track this issue, we can continue the discussion there if needs be.
JazkAllahu khayran.
