### ISSUE TITLE
[Feature] undo engine

### ISSUE THREAD

**Issue by rebinf** [rebinf/QuranVideoMaker#55]
Implement undo/redo

**Comment by Farfighters** [comment]
Is there any update on this, as well as adding the shortcuts for copy and paste?

**Comment by rebinf** [comment]
This is a bit of a biggish task, but I'll see if I can implement it very soon inShaAllah.

**Comment by Farfighters** [comment]
No worries, I just wanted to know inshallah, take your time with it

**Comment by rebinf** [comment]
This feature has been implemented in the latest version.
