### ISSUE TITLE
Add verse numbers to image generator

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#56]
Currently no settings are there for verse numbers with ayah, whenever you have the time after all the other issues, could you add verse numbers tick box like the main software has in export settings. Jazakhallah khair.

**Comment by rebinf** [comment]
I'm sorry, could you clarify a bit more, not sure what you mean by verse numbers, are talking about verse numbers for the translations?

**Comment by Farfighters** [comment]
![image](https://github.com/user-attachments/assets/6842b99d-fae3-4f0f-aecb-1c253d570aa2)

**Comment by Farfighters** [comment]
there is no option for this here:
![image](https://github.com/user-attachments/assets/ba7e0f40-6a04-4844-bae4-cca1a316f291)

**Comment by Farfighters** [comment]
By the way brother, because of the export issues I haven't been able to use the software for our next video, so I was using my usual software. Subhanallah, there is such a big difference between having to do everything manually and with your software. I really appreciate how much you have put in for this project to the point that I feel spoilt, alhamdulillah!

**Comment by rebinf** [comment]
Oh I got it, I will add it InShaAllah.

**Comment by Farfighters** [comment]
Jazakhallah khair!

**Comment by rebinf** [comment]
I'm happy you're finding QVM useful, you know a while ago, I wanted to create a Quran video.
It seemed so difficult, you either had to copy & paste text (ayah's and translations), trying to make it look right, I even looked up an easy way to do it, there was so much you needed to do to make a video, I thought nope I can't do this, there got to be an easier way!
And that is how this project started :)

**Comment by Farfighters** [comment]
Alhamdulillah you took the initiative! Literally this software is only one of two apps I have seen online that can do this, and by far this is the best. May Allah reward you for this!

**Comment by rebinf** [comment]
Happy you like it.
Even if QVM doesn't work properly, you can use the generator and you're half way there :)
Thank you for your kind words.
Ameen ajma'een

**Comment by Farfighters** [comment]
Yes I know, that is what I'm doing now alhamdulillah, that is why I was asking for verse numbers to make it the exact same as the app right now, until the memory issue resolves inshallah

**Comment by rebinf** [comment]
I've just added verse numbers in [v0.0.48](https://github.com/rebinf/QuranVideoMaker/releases/tag/v0.0.48) release.

**Comment by Farfighters** [comment]
Jazakhallah khair, in this version, what else was added, so I can try them as well. I didn't understand some of the other things

**Comment by rebinf** [comment]
I've wrote bullet points in the release description. but here is a brief explanation:

* set verse number bounderies, so you can't put in a number that's lower than 1 and higher than currently selected chapter's verse count (it was crashing when i was changing chapters and forgetting to update `To Verse`.
* Removing clip did not remove the its related track items (causing it to crash) now it asks for a confirmation and removes its related track items.
* verse number option in the generator.

**Comment by Farfighters** [comment]
Jazakhallah khair for explaining. For the removing clip, is this from the media pool or from timeline? Is that what was causing the previous crashes for the latest version?

**Comment by rebinf** [comment]
this is for the clips list/media pool, if you removed a clip there before, the track items would remain, so if you moved the needle or clicked play, it would crash because it couldn't find the clip.
I'm not really sure, but if you removed a clip before and still tried to use its related track items in the timeline, then chances are that's why it crashed.
wa iiyakum

**Comment by Farfighters** [comment]
Ah ok that makes sense now, jazakhallah khair

**Comment by rebinf** [comment]
wa iiyakum
