### ISSUE TITLE
Videos Exported have large sizes

### ISSUE THREAD

**Issue by redaamrmahmoud** [rebinf/QuranVideoMaker#6]
Al slamo alaikom my brother , 

There is a repo including a a video compressor using c# 

you can implement it in your video maker as an option for compressing video.
that will be good if someone wants to share videos and uploading them

link for repo : https://github.com/ahmad-qamar/AQ-Video-Compressor

Inshaa Allah  i may contritbute with you when i got free some time 
May Allah bless you my brother

**Comment by rebinf** [comment]
Wa alaykum salam.

Thanks for the suggestion, once I'm done with some of the rewrite, I will look into this InShaAllah.

Thank you, you too.

**Comment by redaamrmahmoud** [comment]
InShaAllah .
Thank you my friend for replying and good words .
