### ISSUE TITLE
Export quality

### ISSUE THREAD

**Issue by rebinf** [rebinf/QuranVideoMaker#68]
> Assalamualaikum brother. I just wanted to ask whether you had to reduce quality of export to solve memory issues? As now when I exported and put into my other video editor, it detected as 1080p rather than 4K even when I set it as 4K. Also, looking at the videos, they look slightly worse quality than before at same settings. If this isn't related to memory then please set it as separate issue, but I was thinking it might be related to changes in export.

**Comment by rebinf** [comment]
wa alaykum salam.

Memory reduction was not done at the cost of reducing quality, right now when exporting it processes maximum  30-40 frames at  a time, and when they're processed, they're no longer in memory.

As for the quality issue, I just checked, exported video was 4K and detected as 4K by kdenlive.
You may want to check project settings and make sure width is 3840 and height is 2160.

**Comment by Farfighters** [comment]
Ah ok, that makes sense in terms of memory, now it is only taking around 3GB. The export is a lot slower now though, but of course I would rather have this then not being able to use it at all. Whenever you have the time could you look at improving the speed of export inshallah. Maybe increasing the max frames so it is a bit faster? Of course you know better inshallah. Also in terms of export quality, the project is set to correct width and height:
![image](https://github.com/user-attachments/assets/956fe330-bc5c-4e4e-b3f5-ce35eb3bdf5c)
![image](https://github.com/user-attachments/assets/c8ee5d54-c6e5-4b5c-abda-e4ebbd96a0b0)
I will check with other projects and see if it is different inshallah

**Comment by rebinf** [comment]
I didn't notice any speed issues when tested it, seemed to be more or less the same speed.
I've added `Frames Per Batch` option, it's 10 by default, if current queue is greater than 10 * 3, then it waits.
And as for the quality, I didn't see any difference, video resolution should be the same as what you've specified.
Anyway, let me know if you find out anything.

**Comment by Farfighters** [comment]
Jazakhallah khair. I don't really understand the 10*3 part. It's just for my own understanding inshallah. Is this basically how many frames per second? So if I put 30, that is 30 frames per second? And in doing so that increases memory usage? Just for me to understand how this works inshallah, I'm trying to add to my knowledge all the time.

**Comment by rebinf** [comment]
That's not FPS.
Also the way QVM does things, may or may not apply to other video editors, as QVM handles certain things differently.

To explain the process, your video is broken down to frames, for example, your 1 minute video (at 25fps) is 1500 frames, QVM will render every frame and pipe it to ffmpeg with the audio to create the video.
Now if we were to render one frame at a time, it's going to take a long time, that's why we have `Threads` option, which tells QVM how many (or maximum to be more accurate) threads to create and render a  frame in each (`-1` for threads means unlimited, the framework decides max threads to create).
Now problem is that the more frames you render at once the more memory will be used, which it could lead to crashes as the system runs out of memory.
That's where the new batch option comes in, this tells QVM if more than 10 * 3 (this means any specified number of batches times 3, in this case 30) frames are waiting to be processed, then wait.
So the higher the batch number the more frames can be rendered and kept in memory to be processed at any time, and that means more memory usage.
Hope this helps.

**Comment by Farfighters** [comment]
Subhanallah, jazakhallah khair for clearing that up for me, I understand it a lot better now!

**Comment by rebinf** [comment]
Glad i could help.
Wa iiyakum

**Comment by Farfighters** [comment]
In terms of export quality I think everything is fine now. The frames per batch option is very useful jazakhallah khair, of course for longer videos eventually it will just go back to around 10-30 frames even if it is in higher settings, for the reasons you described earlier. Inshallah you can close this issue now.

**Comment by rebinf** [comment]
thanks for letting me know.
jazakAllahu khayr
