### ISSUE TITLE
[Bug] fix audio track and export issues

### ISSUE THREAD

**Issue by rebinf** [rebinf/QuranVideoMaker#7]

**Comment by redaamrmahmoud** [comment]
[2 Surah Al-baqarah empty.zip](https://github.com/rebinf/QuranVideoMaker/files/12208207/2.Surah.Al-baqarah.empty.zip)

Alslamo alaikom , This is a project which has all verses in surah al baqarah according to the reciter Ahmed al Ajmi 

you can go to islamway site and download surah number 2 in the high quality and add it to this project media files

this is maybe the maximum project you can handle where it is 1 hour and 52 minutes , you can use it for tests

**Comment by rebinf** [comment]
Thanks for the project, I will check it out and see.
The audio issue is pretty apparent even without long videos, it doesn't always play at the correct time.

**Comment by redaamrmahmoud** [comment]
Alslamo alikom my brother , 
Sorry if i sent too many issues <3 

![image](https://github.com/rebinf/QuranVideoMaker/assets/98652126/0ffbb6d0-513d-4ef5-85ad-1da5ca273c3a)
Stuck Here (Surah Al-Qasas , maybe 25 minutes at 1080 )

(Some additions you can do : 
1- make the transition optional where i can add or no as a ( checkbox ) 
2- make an option to add a background color to act as a background image where the transition affects only text not the whole frame 

another bugs : 
1 - Define new color doesn't save the new color
2- some mp4 encoded as libx264 ( created by ffmpeg ) takes a long time to be imported and some times it is stuck

And The AutoUpdate , i had a project that i made from the grace of allah thanks to him subahanuh he is our helper
where you can update only the new files 
it check for version via an online raw txt where you can edit any time and if the version not same 
then it goes for an upload system you made on any of the uploadwebsite where you made the file like this
uploadsystemexample.com/rebinf/quranvideo/version2
then it downloads all in version 2 and saves it to the app without downloading the whole app again for github
and the folder version2 should contain the changed files only in the bin of vs project where you can find them by the date modified and take them and put them in their folders as they where in the app and upload them to the system ......

Sorry for the long comment , i know there are more important bugs than those but what i remember i will keep hre to be able to commit later

**Comment by rebinf** [comment]
Wa alaykum salam,

Could I ask you to create separate issues for these things, it would be easier to track all these things in their own separate issues.
I actually am seeing your comment just now as I wasn't aware of any new issues.

Thanks for taking time to write about these issues and improvements.

JazakAllahu Khayran

**Comment by Iam-Muslim** [comment]
Al slam alaikom , 
I have done that elhamdle Allah <3
I hope you are well <3

**Comment by rebinf** [comment]
Wa alaykum salam,

Thank you, I will go through them and see.

JazakAllahu Khayran
