### ISSUE TITLE
Can't edit each individual verse

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#71]
Normally you can double click the verse and a pop up comes up that allows you to edit the verse fully, deleting certain parts or adding more. But for some reason now if I change it, it is not updating as shown:
![image](https://github.com/user-attachments/assets/50d5825c-75ac-4dff-bda2-fe6ee67d9343)
![image](https://github.com/user-attachments/assets/543c205b-8274-4f44-9264-65db6b4ae0b8)
Maybe another feature that would be very useful is adding an 'empty' verse where you can add whatever you want into it, maybe it could be adhkar etc as well. You could have option to add more textboxes (normally you have 1 and if you want to put translation for example you add into new box that comes up separately as it does already). I will make new issue and add this there.
Jazakhallah khair

**Comment by Farfighters** [comment]
Assalamualaikum wbt, jazakhallah khair for implementing the features I asked for so quickly! Just confirming that this hasn't been done yet, right? For some reason, when I export as verses (new feature), it shows up as the modified one, it's just a visual thing. But it is still important to be able to see it visually so it is easier to edit and know whether it has been modified or not inshallah.

**Comment by rebinf** [comment]
wa alaykum salam,
this is due rendered verse cache not being cleared after change.
I've fixed it, it should be available in a few minutes inShaAllah.

**Comment by Farfighters** [comment]
Assalamualaikum wbt, for some reason it is still playing up. If I copy the same verse let's say 5 times, after changing the first one, the rest look the same, even if it has been changes. Must be the same issue as before, maybe it is not clearing because I have made so many?
![image](https://github.com/user-attachments/assets/56530438-7d35-4641-9bfa-10a2bcbeb46e)

**Comment by rebinf** [comment]
wa alaykum salam,
this is due to incorrect cache clearing, which should now be fully resolved in the latest update.

**Comment by rebinf** [comment]
Thanks for reporting this, I think it should be working as expected now.
