### ISSUE TITLE
Add the ability to edit the text in Quran Image Maker as well

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#74]
As said above, ability to change the text as we were able to in previous versions of QVM as well. Maybe under preview there are text boxes where you can edit the text.

**Comment by rebinf** [comment]
This would be difficult to do, as there isn't a track to view and edit each verse.
However, best solution would probably be adding PNG as an export option in QVM itself.

**Comment by rebinf** [comment]
Please check the latest `Export Verses` feature under the `Project` menu.
