### ISSUE TITLE
Ability to set default destination for both QVM and QIM (especially QIM)

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#75]
As said above, also like we have for QVM ability to browse for location to export too as currently we have to copy the location from file manager. This can be hard for those who don't have Windows 11 as Windows 11 all you have to do is find the location and click the top and copy, but in previous Windows (I'm not sure about other systems) there are more steps involved. I know I've added many different requests, but this is what is just on my mind, do whenever you want inshallah.

**Comment by rebinf** [comment]
Unless I misunderstood, you click the "browse" icon in QVM to select a folder, as for QIM I will add that inShaAllah:

![image](https://github.com/user-attachments/assets/0e26f40e-4995-4e13-8334-289b7955ef02)

**Comment by Farfighters** [comment]
No, you are correct, I meant as in the same thing as in QVM.

**Comment by rebinf** [comment]
Thanks for reporting this, this has been resolved.
