### ISSUE TITLE
Have more projects show up in 'Recent Projects' list

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#77]
It is already very useful, but it would be even more useful if there were maybe 5 on there? Because if you went all the way to this tab for recent project, it would make sense that you want to be able to access a few more. Maybe a scroll instead, with 3 showing at a time to take less space on screen? Just a suggestion to make it even better.

**Comment by rebinf** [comment]
The limit is 10, however there was a bug when you saved a project, it wouldn't go to the recent list.
It should do now, please check and let me know.

**Comment by Farfighters** [comment]
Ah ok, it is working now jazakhallah khair

**Comment by rebinf** [comment]
wa iiyakum
