### ISSUE TITLE
When you add new verse using 'Add' Quran feature, it adds it at the start of the timeline

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#78]
Would make it a lot easier if it got added where the last verse ended, or where the white line marker is (I don't know what it's called). Similar to how if I copy a verse and wherever the marker is, it pastes there.

**Comment by rebinf** [comment]
I'll look into this inShaAllah.

**Comment by rebinf** [comment]
now it adds verses at needle position by default.
