### ISSUE TITLE
Exporting verses as PNGs not working properly

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#80]
I am repeating many verses again and again, what happens is that when I exported it, it only exports the last repetition of that verse, if there were more than one. Like:
![image](https://github.com/user-attachments/assets/3cd57e5a-53fd-4fa6-ba19-8aed5fa83d24)
![image](https://github.com/user-attachments/assets/117d16b7-fe0b-49f7-bba7-3d8f7c5a7773)
Both are same verse but I split into 2. Only last one exported.

**Comment by rebinf** [comment]
This is due to "verse part" naming issue, which should be resolved in the latest update.

**Comment by Farfighters** [comment]
This is working now alhamdulillah, though projects from previous versions still use old naming system so don't work. Jazakhallah khair for this!

**Comment by rebinf** [comment]
For projects created with an older version, there is now `Fix Verse Numbers` under `Quran` menu.
wa iiaykum

**Comment by Farfighters** [comment]
Just tried latest verison, jazakhallah khair all verses fixed now!

**Comment by rebinf** [comment]
Wa iiaykum, thank you for reporting all the issues
