### ISSUE TITLE
Waveform not accurate

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#82]
For some reason the waveform isn't accurate for timings. At start it was fine, but slowly it got stretched slightly to the point that at the end it was nearly half a verse off. This is my first time using waveform when using auto verse, and I realised that the verses weren't properly synced as I was going by waveform and not sound. Maybe similar thing that happened to videos earlier (they were stretched). Confusing thing is that on timeline it looks like same length, maybe that is also not showing correctly?

**Comment by Farfighters** [comment]
Use a very long audio (10mins+) to see this more obviously when looking at the end

**Comment by rebinf** [comment]
This should be fixed now, can you check and let me know please.

**Comment by Farfighters** [comment]
Waveform working now, but even before if you were to adjust audio (cut off from end), waveform moves instead of getting cut off , so it doesn't work if you change the audio, but everything else is fine. Jazakhallah khair for undo/redo, already very useful!

**Comment by rebinf** [comment]
Thank you for letting me know.
There is a few issues open regarding audio track issues, I will deal with them soon inShaAllah.
