### ISSUE TITLE
[Export Improvement]

### ISSUE THREAD

**Issue by Iam-Muslim** [rebinf/QuranVideoMaker#9]
Alslam alaikom my brother , 

- [Hardware accelerated option ) 

make a checkbox in the export windows to activate the hardware acceleration option using ffmpeg for faster exporting (uses gpu along cpu )

`options.hardwareaccelerated(hardwareaccelerated.auto);`

maybe that is the code to add ( as i remember with  the grace of Allah )

- [Speed Preset ]

Make an listbox in the export windows to choose between different speed preset of ffmpeg ( slow , meduim , fast , ultra fast ) 
`options.WithSpeedPreset(Speed.UltraFast);`

this is an example from the grace of Allah subhanuh

**Comment by Iam-Muslim** [comment]
Exporting Failed ( 1 hour and 51 minutes 1920x1080 )
![image](https://github.com/rebinf/QuranVideoMaker/assets/98652126/da7c0a6c-eb24-45e3-bdf9-ee00cf49057f)

**Comment by rebinf** [comment]
I added encoding speed and hardware acceleration options.
However I've commented out the hardware acceleration options as it crashes for some reason.
I'll close this in favor of #22

**Comment by rebinf** [comment]
Also you have very likely ran out of RAM.
I tried to export Baqarah, I cancelled it as it took too long, but it used ~50GB of RAM!
