### ISSUE TITLE
Audio doesn't start at right place after moving it

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#91]
When I add audio into timeline, but not right at the start, the move it to the start after, the audio plays from where I first put the audio. Didn't notice it until I put it very far from start, then moved it to the start. It wouldn't play properly after that.

**Comment by Farfighters** [comment]
Actually, audio is a bit messed up right now. If I place it in middle of track then play it, it will play as if it was placed at start. So waveform isn't completely accurate again

**Comment by rebinf** [comment]
As mentioned before the audio side of things only works properly if you already have a prepared audio file and using it as is.
There are a few audio related open issues, I will look into it soon insha'Allah.
