### ISSUE TITLE
Add option to remove certain things (e.g. translation) after making the verses

### ISSUE THREAD

**Issue by Farfighters** [rebinf/QuranVideoMaker#92]
I make shorts from the long form videos I make, so I just go back to old projects and change settings, but I can't remove the translation (shorts perform better without translation), so I have to redo the verses again. If we could edit the actual verses in the same way we can with settings that would be very useful and save a lot of time, jazakhallah khair!

**Comment by rebinf** [comment]
I'll have a look and see what I can do.
Wa iiyakum

**Comment by rebinf** [comment]
Alhamdulillah I think I've come up with a better solution :)
Now you can do the video once, with multiple translations, then export all translations separately at once.

Also now, if you add/remove translations in Quran Settings, it will be added/removed from the Quran track.

**Comment by Farfighters** [comment]
Jazakhallah khair brother for your efforts! This is definitely extremely helpful for me! Could you explain how to use the multiple video export option? I've tried with all the different options but I have got the exact same video in all the different options.

**Comment by rebinf** [comment]
You can create a project as normal, adding multiple different translations, like english, kurdish, urdu etc...

If you change "All Translations" option, you can see what the video with each translation looks like.

Once you're ready to export the project, in the export window, select "Separate Videos" from the first dropdown, and this should create a video for each tranalation.
Hope this makes sense.
Let me know how it goes.

**Comment by Farfighters** [comment]
Ah, does this only work if you have more than 1 translation (not including arabic)? Becuase if you only have 1 english one I think it makes no effect?

**Comment by rebinf** [comment]
This is only useful if you have more than one translation and want to create separate videos for each translation.

Say you want to do 5 different languages, the old way would've been creating 5 separate projects for each translation, and export each project.

The new way is creating one project with 5 different translations, and automatically creating a separate video for each tranalation on export, where everything is going to be the same except it would be a different translation for each video.

If you have one translation, it will produce only one video even if you select "separate videos" option.

Hope this helps.

**Comment by Farfighters** [comment]
Ah, now I understand what you are saying. Yes, that's very useful for making videos with different languages. Jazakhallah khair!

**Comment by rebinf** [comment]
Glad you're finding it useful.
Wa iiyakum
